import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import {
  AdminError,
  fetchFestivalMap,
  fetchLineupDashboard,
  saveFestivalMap,
  uploadMapAsset,
  type FestivalMapInput,
} from "./adminApi";
import { AdminHeader, AdminLoading, AdminErrorState, AdminBanner } from "./AdminUi";
import { fitAffine, geoToSvg, residual, svgToGeo, type Affine } from "../map/transform";

interface ControlPoint {
  id: string;
  x: number; // canvas-space pixel
  y: number;
  lng: number;
  lat: number;
}
interface EditStage {
  name: string;
  lng: number | null;
  lat: number | null;
  iconUrl: string | null;
  iconLng: number | null;
  iconLat: number | null;
  iconScale: number;
  isSpoiler: boolean;
}
type ClickMode =
  | { kind: "idle" }
  | { kind: "control" }
  | { kind: "stage"; name: string }
  | { kind: "stage-icon"; name: string };

const newId = (): string => Math.random().toString(36).slice(2, 9);

/**
 * R11.1c map editor (DEC-064): georeference a base raster (>= 3 control points -> least-squares
 * affine) and place each stage's coordinate, with a live preview using the exact runtime geoToSvg.
 * Saves the MapTransformDoc the app consumes. Map ART is generated by the local spike; this places.
 */
export function AdminMapEditorScreen(): JSX.Element {
  const { id: festivalId = "" } = useParams();
  const [festivalName, setFestivalName] = useState("");
  const [festivalSlug, setFestivalSlug] = useState("");
  const [venue, setVenue] = useState("");
  const [source, setSource] = useState("OpenStreetMap contributors (ODbL)");
  const [baseNightUrl, setBaseNightUrl] = useState("");
  const [baseDayUrl, setBaseDayUrl] = useState("");
  const [canvas, setCanvas] = useState<{ width: number; height: number } | null>(null);
  const [affine, setAffine] = useState<Affine | null>(null);
  const [controls, setControls] = useState<ControlPoint[]>([]);
  const [stages, setStages] = useState<EditStage[]>([]);
  const [mode, setMode] = useState<ClickMode>({ kind: "idle" });

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [banner, setBanner] = useState<{ tone: "ok" | "warn" | "info"; icon: string; message: string } | null>(null);
  const [saving, setSaving] = useState(false);

  const load = useCallback(
    async (signal?: AbortSignal): Promise<void> => {
      setLoading(true);
      try {
        const [{ map }, dash] = await Promise.all([
          fetchFestivalMap(festivalId, signal),
          fetchLineupDashboard(festivalId, signal).catch(() => null),
        ]);
        if (signal?.aborted) return;

        const name = dash?.festival.name ?? map?.transform.festival ?? festivalId;
        setFestivalName(name);
        setFestivalSlug(dash?.festival.slug ?? map?.transform.festival ?? festivalId);
        setVenue(map?.transform.venue ?? dash?.festival.name ?? "");
        setSource(map?.transform.source ?? "OpenStreetMap contributors (ODbL)");
        setBaseNightUrl(map?.baseNightUrl ?? "");
        setBaseDayUrl(map?.baseDayUrl ?? "");
        setCanvas(map?.transform.canvas ?? null);
        setAffine(map?.transform.affine ?? null);

        // Stage list comes from the real lineup; coords prefill from any existing transform (by name).
        const byName = new Map((map?.transform.stages ?? []).map((s) => [s.name, s] as const));
        const stageNames = dash?.stages.map((s) => s.name) ?? [...byName.keys()];
        setStages(
          stageNames.map((nm) => {
            const g = byName.get(nm);
            return {
              name: nm,
              lng: g?.lng ?? null,
              lat: g?.lat ?? null,
              iconUrl: g?.iconUrl ?? null,
              iconLng: g?.iconLng ?? null,
              iconLat: g?.iconLat ?? null,
              iconScale: g?.iconScale ?? 1,
              isSpoiler: g?.isSpoiler ?? false,
            };
          })
        );
        setError(null);
      } catch (err) {
        if (!signal?.aborted) setError(err instanceof AdminError ? `Couldn't load the map (${err.status}).` : "Couldn't load the map.");
      } finally {
        if (!signal?.aborted) setLoading(false);
      }
    },
    [festivalId]
  );

  useEffect(() => {
    const ctrl = new AbortController();
    void load(ctrl.signal);
    return () => ctrl.abort();
  }, [load]);

  // Default the canvas to the night raster's natural size when no transform set one yet.
  useEffect(() => {
    if (canvas || !baseNightUrl) return;
    const img = new Image();
    img.onload = () => setCanvas({ width: img.naturalWidth, height: img.naturalHeight });
    img.src = baseNightUrl;
  }, [baseNightUrl, canvas]);

  const validControls = useMemo(
    () => controls.filter((c) => Number.isFinite(c.x) && Number.isFinite(c.y) && c.lng !== 0 && c.lat !== 0),
    [controls]
  );
  const fit = useMemo(() => {
    if (validControls.length < 3) return null;
    const src = validControls.map((c) => ({ lng: c.lng, lat: c.lat }));
    const dst = validControls.map((c) => ({ x: c.x, y: c.y }));
    const a = fitAffine(src, dst);
    return { affine: a, residual: residual(a, src, dst) };
  }, [validControls]);

  const placedStages = useMemo(() => stages.filter((s) => s.lng !== null && s.lat !== null), [stages]);

  function onCanvasClick(e: React.MouseEvent<SVGSVGElement>): void {
    if (!canvas || mode.kind === "idle") return;
    const rect = e.currentTarget.getBoundingClientRect();
    const x = ((e.clientX - rect.left) / rect.width) * canvas.width;
    const y = ((e.clientY - rect.top) / rect.height) * canvas.height;
    if (mode.kind === "control") {
      setControls((cs) => [...cs, { id: newId(), x: round(x, 1), y: round(y, 1), lng: 0, lat: 0 }]);
      setBanner({ tone: "info", icon: "place", message: "Control point dropped — type its real lng/lat." });
    } else if (mode.kind === "stage") {
      if (!affine) {
        setBanner({ tone: "warn", icon: "warning", message: "Fit the affine first, then click to place stages." });
        return;
      }
      const geo = svgToGeo(affine, x, y);
      if (!geo) return;
      const name = mode.name;
      setStages((ss) => ss.map((s) => (s.name === name ? { ...s, lng: round(geo[0], 7), lat: round(geo[1], 7) } : s)));
    } else if (mode.kind === "stage-icon") {
      if (!affine) {
        setBanner({ tone: "warn", icon: "warning", message: "Fit the affine first, then click to position the icon." });
        return;
      }
      const geo = svgToGeo(affine, x, y);
      if (!geo) return;
      const name = mode.name;
      setStages((ss) => ss.map((s) => (s.name === name ? { ...s, iconLng: round(geo[0], 7), iconLat: round(geo[1], 7) } : s)));
      setBanner({ tone: "ok", icon: "check", message: `Icon for "${name}" positioned.` });
    }
  }

  function applyFit(): void {
    if (!fit) return;
    setAffine(fit.affine);
    setBanner({ tone: "ok", icon: "check", message: `Affine fitted — max error ${fit.residual.maxPx.toFixed(1)} px.` });
  }

  async function onUpload(slot: "night" | "day", file: File): Promise<void> {
    setBanner({ tone: "info", icon: "cloud_upload", message: `Uploading ${slot} base…` });
    try {
      const { url } = await uploadMapAsset(festivalId, slot, file);
      if (slot === "night") setBaseNightUrl(url);
      else setBaseDayUrl(url);
      setBanner({ tone: "ok", icon: "cloud_done", message: `${slot} base uploaded.` });
    } catch (err) {
      setBanner({ tone: "warn", icon: "error", message: err instanceof AdminError ? err.message : "Upload failed." });
    }
  }

  async function onSave(): Promise<void> {
    if (!canvas || !affine) {
      setBanner({ tone: "warn", icon: "warning", message: "A base image + a fitted affine are required to save." });
      return;
    }
    if (!baseNightUrl) {
      setBanner({ tone: "warn", icon: "warning", message: "A night base image is required." });
      return;
    }
    setSaving(true);
    setBanner(null);
    const lngs = placedStages.map((s) => s.lng!);
    const lats = placedStages.map((s) => s.lat!);
    const bbox =
      placedStages.length > 0
        ? { west: Math.min(...lngs), east: Math.max(...lngs), south: Math.min(...lats), north: Math.max(...lats) }
        : { west: 0, east: 0, south: 0, north: 0 };
    const input: FestivalMapInput = {
      assetSlug: festivalSlug || festivalId,
      baseNightKey: baseNightUrl,
      baseDayKey: baseDayUrl || baseNightUrl,
      transform: {
        festival: festivalSlug || festivalId,
        venue: venue || festivalName,
        canvas,
        bbox,
        affine,
        stages: placedStages.map((s) => ({
          name: s.name,
          lng: s.lng!,
          lat: s.lat!,
          matched: true,
          ...(s.iconUrl ? { iconUrl: s.iconUrl } : {}),
          ...(s.iconLng != null ? { iconLng: s.iconLng } : {}),
          ...(s.iconLat != null ? { iconLat: s.iconLat } : {}),
          ...(s.iconScale !== 1 ? { iconScale: s.iconScale } : {}),
          ...(s.isSpoiler ? { isSpoiler: true } : {}),
        })),
        source,
      },
    };
    try {
      const r = await saveFestivalMap(festivalId, input);
      setBanner({ tone: "ok", icon: "check_circle", message: `Map saved (revision ${r.revision}). ${placedStages.length} stages placed.` });
    } catch (err) {
      setBanner({ tone: "warn", icon: "error", message: err instanceof AdminError ? err.message : "Couldn't save the map." });
    } finally {
      setSaving(false);
    }
  }

  return (
    <div>
      <AdminHeader
        eyebrow={festivalName || "Map"}
        title="Map editor"
        action={
          <button className="btn btn-primary" type="button" onClick={onSave} disabled={saving || !affine || !canvas}>
            <span className={`ms${saving ? " admin-state-spin" : ""}`}>save</span>
            {saving ? "Saving…" : "Save map"}
          </button>
        }
      />

      {banner ? (
        <AdminBanner tone={banner.tone} icon={banner.icon}>
          {banner.message}
        </AdminBanner>
      ) : null}

      {error ? (
        <AdminErrorState message={error} />
      ) : loading ? (
        <AdminLoading />
      ) : (
        <div className="map-editor">
          <div className="map-editor-canvas card">
            <div className="map-editor-modes">
              <ModeButton label="Pan" icon="pan_tool" active={mode.kind === "idle"} onClick={() => setMode({ kind: "idle" })} />
              <ModeButton
                label="Add control point"
                icon="add_location"
                active={mode.kind === "control"}
                onClick={() => setMode({ kind: "control" })}
              />
              <span className="admin-muted map-editor-hint">
                {mode.kind === "stage" ? `Click the map to place "${mode.name}"` : mode.kind === "stage-icon" ? `Click to position icon for "${mode.name}"` : mode.kind === "control" ? "Click a known landmark on the map" : "Pick a tool to edit"}
              </span>
            </div>
            {baseNightUrl && canvas ? (
              <svg
                className="map-editor-svg"
                viewBox={`0 0 ${canvas.width} ${canvas.height}`}
                onClick={onCanvasClick}
                role="img"
                aria-label="map canvas"
              >
                <image href={baseNightUrl} x={0} y={0} width={canvas.width} height={canvas.height} />
                {controls.map((c) => (
                  <g key={c.id} className="map-cp">
                    <circle cx={c.x} cy={c.y} r={Math.max(6, canvas.width / 110)} />
                    <line x1={c.x - 14} y1={c.y} x2={c.x + 14} y2={c.y} />
                    <line x1={c.x} y1={c.y - 14} x2={c.x} y2={c.y + 14} />
                  </g>
                ))}
                {affine
                  ? placedStages.map((s) => {
                      const [px, py] = geoToSvg(affine, s.lng!, s.lat!);
                      const r = Math.max(7, canvas.width / 90);
                      const hasIcon = s.iconUrl && s.iconLng != null && s.iconLat != null;
                      const iconPos = hasIcon ? geoToSvg(affine, s.iconLng!, s.iconLat!) : null;
                      const iconSize = (s.iconScale ?? 1) * canvas.width * 0.08;
                      return (
                        <g key={s.name}>
                          {iconPos && (
                            <image
                              href={s.iconUrl!}
                              x={iconPos[0] - iconSize / 2}
                              y={iconPos[1] - iconSize / 2}
                              width={iconSize}
                              height={iconSize}
                              opacity={0.85}
                              className="map-editor-stage-icon"
                            />
                          )}
                          <g className={`map-pin${(mode.kind === "stage" || mode.kind === "stage-icon") && mode.name === s.name ? " on" : ""}`}>
                            <circle cx={px} cy={py} r={r} />
                            <text x={px} y={py - r - 4} textAnchor="middle">
                              {s.name}
                            </text>
                          </g>
                        </g>
                      );
                    })
                  : null}
              </svg>
            ) : (
              <div className="map-editor-empty admin-muted">
                No base image yet. Add a night base URL or upload one to begin georeferencing.
              </div>
            )}
          </div>

          <div className="map-editor-panel">
            <BasePanel
              night={baseNightUrl}
              day={baseDayUrl}
              onNight={setBaseNightUrl}
              onDay={setBaseDayUrl}
              onUpload={onUpload}
              venue={venue}
              onVenue={setVenue}
            />
            <ControlsPanel
              controls={controls}
              fit={fit}
              affineSet={!!affine}
              onAdd={() => {
                setMode({ kind: "control" });
                setControls((cs) => [...cs, { id: newId(), x: 0, y: 0, lng: 0, lat: 0 }]);
              }}
              onChange={(id, patch) => setControls((cs) => cs.map((c) => (c.id === id ? { ...c, ...patch } : c)))}
              onRemove={(id) => setControls((cs) => cs.filter((c) => c.id !== id))}
              onApply={applyFit}
            />
            <StagesPanel
              stages={stages}
              festivalId={festivalId}
              affineSet={!!affine}
              activeName={mode.kind === "stage" || mode.kind === "stage-icon" ? mode.name : null}
              activeMode={mode.kind === "stage" ? "stage" : mode.kind === "stage-icon" ? "icon" : null}
              onPick={(name) => setMode((m) => (m.kind === "stage" && m.name === name ? { kind: "idle" } : { kind: "stage", name }))}
              onPickIcon={(name) => setMode((m) => (m.kind === "stage-icon" && m.name === name ? { kind: "idle" } : { kind: "stage-icon", name }))}
              onChange={(name, patch) => setStages((ss) => ss.map((s) => (s.name === name ? { ...s, ...patch } : s)))}
              onBanner={setBanner}
            />
          </div>
        </div>
      )}
    </div>
  );
}

function ModeButton({ label, icon, active, onClick }: { label: string; icon: string; active: boolean; onClick: () => void }): JSX.Element {
  return (
    <button className={`btn btn-sm ${active ? "btn-primary" : "btn-ghost"}`} type="button" onClick={onClick} title={label}>
      <span className="ms">{icon}</span>
      {label}
    </button>
  );
}

function BasePanel({
  night,
  day,
  onNight,
  onDay,
  onUpload,
  venue,
  onVenue,
}: {
  night: string;
  day: string;
  onNight: (v: string) => void;
  onDay: (v: string) => void;
  onUpload: (slot: "night" | "day", file: File) => void;
  venue: string;
  onVenue: (v: string) => void;
}): JSX.Element {
  return (
    <section className="card admin-panel map-editor-section">
      <div className="admin-section">
        <span className="ms">image</span> Base raster
      </div>
      <UrlUploadRow label="Night base URL" slot="night" value={night} onChange={onNight} onUpload={onUpload} />
      <UrlUploadRow label="Day base URL (optional)" slot="day" value={day} onChange={onDay} onUpload={onUpload} />
      <div className="admin-field">
        <label className="label">Venue</label>
        <input className="field selectable" value={venue} onChange={(e) => onVenue(e.target.value)} placeholder="De Schorre" />
      </div>
    </section>
  );
}

function UrlUploadRow({
  label,
  slot,
  value,
  onChange,
  onUpload,
}: {
  label: string;
  slot: "night" | "day";
  value: string;
  onChange: (v: string) => void;
  onUpload: (slot: "night" | "day", file: File) => void;
}): JSX.Element {
  const fileRef = useRef<HTMLInputElement>(null);
  return (
    <div className="admin-field">
      <label className="label">{label}</label>
      <div className="map-editor-url-row">
        <input className="field selectable" value={value} onChange={(e) => onChange(e.target.value)} placeholder="https://… or /media/…" />
        <button className="btn btn-ghost btn-sm" type="button" onClick={() => fileRef.current?.click()} title="Upload to R2">
          <span className="ms">upload</span>
        </button>
        <input
          ref={fileRef}
          type="file"
          accept="image/webp,image/png,image/jpeg"
          hidden
          onChange={(e) => {
            const f = e.target.files?.[0];
            if (f) onUpload(slot, f);
            e.target.value = "";
          }}
        />
      </div>
    </div>
  );
}

function ControlsPanel({
  controls,
  fit,
  affineSet,
  onAdd,
  onChange,
  onRemove,
  onApply,
}: {
  controls: ControlPoint[];
  fit: { affine: Affine; residual: { maxPx: number; meanPx: number } } | null;
  affineSet: boolean;
  onAdd: () => void;
  onChange: (id: string, patch: Partial<ControlPoint>) => void;
  onRemove: (id: string) => void;
  onApply: () => void;
}): JSX.Element {
  return (
    <section className="card admin-panel map-editor-section">
      <div className="admin-section">
        <span className="ms">my_location</span> Georeference
      </div>
      <p className="admin-muted-p">
        Add 3+ control points: click a known landmark on the map, then enter its real longitude/latitude. A least-squares
        affine is fitted. {affineSet ? "An affine is currently set." : "No affine yet."}
      </p>
      <table className="admin-table map-editor-cp-table">
        <thead>
          <tr>
            <th>x</th>
            <th>y</th>
            <th>lng</th>
            <th>lat</th>
            <th />
          </tr>
        </thead>
        <tbody>
          {controls.map((c) => (
            <tr key={c.id}>
              <td>
                <NumCell value={c.x} onChange={(v) => onChange(c.id, { x: v })} />
              </td>
              <td>
                <NumCell value={c.y} onChange={(v) => onChange(c.id, { y: v })} />
              </td>
              <td>
                <NumCell value={c.lng} step="any" onChange={(v) => onChange(c.id, { lng: v })} />
              </td>
              <td>
                <NumCell value={c.lat} step="any" onChange={(v) => onChange(c.id, { lat: v })} />
              </td>
              <td>
                <button className="btn btn-ghost btn-sm" type="button" onClick={() => onRemove(c.id)} title="Remove">
                  <span className="ms">delete</span>
                </button>
              </td>
            </tr>
          ))}
          {controls.length === 0 ? (
            <tr>
              <td colSpan={5} className="admin-empty-cell">
                No control points yet.
              </td>
            </tr>
          ) : null}
        </tbody>
      </table>
      <div className="map-editor-cp-actions">
        <button className="btn btn-ghost btn-sm" type="button" onClick={onAdd}>
          <span className="ms">add</span> Add row
        </button>
        <button className="btn btn-primary btn-sm" type="button" onClick={onApply} disabled={!fit}>
          <span className="ms">auto_fix_high</span> Fit affine
        </button>
        {fit ? (
          <span className={`admin-pill ${fit.residual.maxPx < 3 ? "ok" : fit.residual.maxPx < 12 ? "warn" : "danger"}`}>
            max {fit.residual.maxPx.toFixed(1)} px · mean {fit.residual.meanPx.toFixed(1)} px
          </span>
        ) : (
          <span className="admin-muted">need 3 valid points</span>
        )}
      </div>
    </section>
  );
}

function StagesPanel({
  stages,
  festivalId,
  affineSet,
  activeName,
  activeMode,
  onPick,
  onPickIcon,
  onChange,
  onBanner,
}: {
  stages: EditStage[];
  festivalId: string;
  affineSet: boolean;
  activeName: string | null;
  activeMode: "stage" | "icon" | null;
  onPick: (name: string) => void;
  onPickIcon: (name: string) => void;
  onChange: (name: string, patch: Partial<EditStage>) => void;
  onBanner: (b: { tone: "ok" | "warn" | "info"; icon: string; message: string } | null) => void;
}): JSX.Element {
  const placed = stages.filter((s) => s.lng !== null && s.lat !== null).length;
  const fileRefs = useRef<Map<string, HTMLInputElement>>(new Map());

  async function handleIconUpload(stageName: string, file: File): Promise<void> {
    onBanner({ tone: "info", icon: "cloud_upload", message: `Uploading icon for ${stageName}…` });
    try {
      const { url } = await uploadMapAsset(festivalId, "night", file);
      onChange(stageName, { iconUrl: url });
      onBanner({ tone: "ok", icon: "cloud_done", message: `Icon for "${stageName}" uploaded.` });
    } catch (err) {
      onBanner({ tone: "warn", icon: "error", message: err instanceof AdminError ? err.message : "Upload failed." });
    }
  }

  return (
    <section className="card admin-panel map-editor-section">
      <div className="admin-section">
        <span className="ms">festival</span> Stages · {placed}/{stages.length} placed
      </div>
      <div className="map-editor-stages-list">
        {stages.map((s) => {
          const isActive = activeName === s.name;
          return (
            <div key={s.name} className={`map-editor-stage-card${isActive ? " active" : ""}`}>
              <div className="map-editor-stage-row">
                <span className="admin-cell-title">{s.name}</span>
                <div className="map-editor-stage-actions">
                  <button
                    className={`btn btn-sm ${isActive && activeMode === "stage" ? "btn-primary" : "btn-ghost"}`}
                    type="button"
                    onClick={() => onPick(s.name)}
                    disabled={!affineSet}
                    title="Place stage marker"
                  >
                    <span className="ms">place</span>
                  </button>
                  <label className="map-editor-spoiler-toggle">
                    <input
                      type="checkbox"
                      checked={s.isSpoiler}
                      onChange={(e) => onChange(s.name, { isSpoiler: e.target.checked })}
                    />
                    <span className="ms" style={{ fontSize: 16, color: s.isSpoiler ? "#e85d04" : undefined }}>
                      {s.isSpoiler ? "visibility_off" : "visibility"}
                    </span>
                    <span className="admin-muted" style={{ fontSize: 11 }}>Spoiler</span>
                  </label>
                </div>
              </div>
              <div className="map-editor-stage-coords">
                <NumCell value={s.lng} step="any" onChange={(v) => onChange(s.name, { lng: v })} />
                <NumCell value={s.lat} step="any" onChange={(v) => onChange(s.name, { lat: v })} />
              </div>
              <div className="map-editor-stage-icon-section">
                <div className="map-editor-stage-icon-preview">
                  {s.iconUrl ? (
                    <img src={s.iconUrl} alt={`${s.name} icon`} className="map-editor-icon-thumb" />
                  ) : (
                    <span className="admin-muted" style={{ fontSize: 11 }}>No icon</span>
                  )}
                </div>
                <div className="map-editor-stage-icon-controls">
                  <button
                    className="btn btn-ghost btn-sm"
                    type="button"
                    onClick={() => fileRefs.current.get(s.name)?.click()}
                    title="Upload icon"
                  >
                    <span className="ms">upload</span> Icon
                  </button>
                  <input
                    ref={(el) => { if (el) fileRefs.current.set(s.name, el); }}
                    type="file"
                    accept="image/webp,image/png,image/jpeg"
                    hidden
                    onChange={(e) => {
                      const f = e.target.files?.[0];
                      if (f) void handleIconUpload(s.name, f);
                      e.target.value = "";
                    }}
                  />
                  {s.iconUrl && (
                    <>
                      <button
                        className={`btn btn-sm ${isActive && activeMode === "icon" ? "btn-primary" : "btn-ghost"}`}
                        type="button"
                        onClick={() => onPickIcon(s.name)}
                        disabled={!affineSet}
                        title="Position icon on map"
                      >
                        <span className="ms">pin_drop</span> Position
                      </button>
                      <div className="map-editor-icon-scale">
                        <label className="admin-muted" style={{ fontSize: 10 }}>Scale</label>
                        <input
                          type="range"
                          min="0.3"
                          max="3"
                          step="0.1"
                          value={s.iconScale}
                          onChange={(e) => onChange(s.name, { iconScale: Number(e.target.value) })}
                        />
                        <span style={{ fontSize: 11 }}>{s.iconScale.toFixed(1)}x</span>
                      </div>
                      <button
                        className="btn btn-ghost btn-sm"
                        type="button"
                        onClick={() => onChange(s.name, { iconUrl: null, iconLng: null, iconLat: null })}
                        title="Remove icon"
                      >
                        <span className="ms">delete</span>
                      </button>
                    </>
                  )}
                </div>
              </div>
            </div>
          );
        })}
        {stages.length === 0 ? (
          <p className="admin-muted">No stages — import the lineup first.</p>
        ) : null}
      </div>
    </section>
  );
}

function NumCell({
  value,
  onChange,
  step,
}: {
  value: number | null;
  onChange: (v: number) => void;
  step?: string;
}): JSX.Element {
  return (
    <input
      className="field selectable map-editor-num"
      type="number"
      step={step}
      value={value === null ? "" : value}
      onChange={(e) => onChange(e.target.value === "" ? 0 : Number(e.target.value))}
    />
  );
}

function round(n: number, dp: number): number {
  const f = 10 ** dp;
  return Math.round(n * f) / f;
}
